name: Smoke: PTN Portal is live
on:
  schedule: [ { cron: "0 */6 * * *" } ]
  workflow_dispatch:
permissions: { contents: read }
jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -e
          URL="https://artistichorizonx-web.github.io/ptn-portal/"
          echo "Probing $URL"
          for i in 1 2 3 4 5; do
            curl -fsSL "$URL" | grep -qi "PTN Portal" && { echo "OK"; exit 0; }
            sleep 8
          done
          echo "Smoke FAILED"; exit 1
